### ISSUE TITLE
Downloaded example workflow for ComfyUI and it fails

### ISSUE THREAD

**Issue by vicitooo** [TencentARC/MotionCtrl#12]
First of all, great work TencentARC team! We love it!

I know that this is not the repo on ComfyUI node. https://github.com/chaojie/ComfyUI-MotionCtrl but since there I can't put in a Issue I have to ask here.

I download the example workflow and I get this error. Any ideas?

Motionctrl Sample Simple:
- Failed to convert an input value to a INT value: context_overlap, https://chaojie.github.io/ComfyUI-MotionCtrl/tools/draw.html, invalid literal for int() with base 10: 'https://chaojie.github.io/ComfyUI-MotionCtrl/tools/draw.html'

**Comment by PaulCollingwood** [comment]
where it says null on one of the fields, put a 1 in there. context length.

**Comment by gxbsyxh** [comment]
> where it says null on one of the fields, put a 1 in there. context length.

I have the same problem. Help me

**Comment by gxbsyxh** [comment]
![K$4G U942@F{T8`A4H E9BJ](https://github.com/TencentARC/MotionCtrl/assets/148219027/1513d710-ca2f-4f51-9a57-b58b24fac91f)

**Comment by vicitooo** [comment]
There was a NaN in context overlap. I swapped it to 4 and it worked. Thanks!
