### ISSUE TITLE
Pretrained model produces noises

### ISSUE THREAD

**Issue by SnowdenLee** [TencentARC/MotionCtrl#13]
Hi @wzhouxiff , 
thanks for the interesting work!
I downloaded the model here https://huggingface.co/TencentARC/MotionCtrl/blob/main/motionctrl_svd.ckpt for SVD+MotionCtrl inference. All keys add up, but the results are basically noises. Do you maybe have an idea what causes this? Thanks a lot!

![image](https://github.com/TencentARC/MotionCtrl/assets/49041089/fc226a21-6561-45ed-8f23-d517b2ac3eae)

![image](https://github.com/TencentARC/MotionCtrl/assets/49041089/3909b01a-c716-4148-afb8-e8e79384729b)

**Comment by Netanel-Tamir** [comment]
Hi!
I've encountered the same issue. How did you solve it?

**Comment by SnowdenLee** [comment]
Hi @Netanel-Tamir , I managed to fix the issue by using torch 2.0.1. Seems like a CUDA compatibility problem.

**Comment by Netanel-Tamir** [comment]
Thanks @SnowdenLee, can you send the list of packages and versions that worked for you?

**Comment by SnowdenLee** [comment]
Hi @Netanel-Tamir 
Here is the full list [requirement.txt](https://github.com/TencentARC/MotionCtrl/files/14125947/requirement.txt), there are some redundant packages that are not used by this repo though.

**Comment by Netanel-Tamir** [comment]
Thanks for the help!

**Comment by flysssss** [comment]
@SnowdenLee  I've encountered the same issue.  Can you tell me your successful CUDA version？I tried to upgrade torch 2.0.1 with the version you provided, and a CUDA kernel error occurred while generating reasoning
![Uploading image.png…]()

**Comment by flysssss** [comment]
![image](https://github.com/TencentARC/MotionCtrl/assets/100752067/50746aee-8d18-49bd-82bb-054f9fce354f)

**Comment by flysssss** [comment]
![image](https://github.com/TencentARC/MotionCtrl/assets/100752067/bf1cc473-56f4-4eb0-b2c5-03407309ccf3)

**Comment by wzhouxiff** [comment]
Our environment is following the requirements provided by SVD:
https://github.com/Stability-AI/generative-models/blob/0.0.1/requirements_pt13.txt
https://github.com/Stability-AI/generative-models/blob/0.0.1/requirements_pt2.txt
