### ISSUE TITLE
Noises about  MotionCtrl-SVD

### ISSUE THREAD

**Issue by flysssss** [TencentARC/MotionCtrl#23]
@wzhouxiff Thanks for the interesting work!
When I reproduce the SVD version，the results are basically noises.
![image](https://github.com/TencentARC/MotionCtrl/assets/100752067/6ccfe5c5-fea6-4448-a3da-d4ae133ef232)
 
Problem consistency #13 

the Demo of huggingface  is a Erro
![image](https://github.com/TencentARC/MotionCtrl/assets/100752067/71b4c3de-43df-4fe5-a91e-5e7b0285c4ac)

There is another problem. The prompt resolution of the gradient interface is 576x1024, but the background prompt model input resolution is 512x1024，What is the correct input resolution?
![image](https://github.com/TencentARC/MotionCtrl/assets/100752067/05ae687e-048a-4ece-a55a-f14f6573bb29)

Finally, we hope to have a Dockerfile file or image to enable SVD to run completely.

**Comment by flysssss** [comment]
Finally, I have SVD  environment，it works well up there

**Comment by danier97** [comment]
Hi there, how did you solve the problem? What does your SVD environment look like? Thank you very much!
