### ISSUE TITLE
Custom Trajectories without ParticleSfm

### ISSUE THREAD

**Issue by fan23j** [TencentARC/MotionCtrl#34]
Hello,

I am having some issues utilizing particlesfm to construct trajectories, so I wanted to ask about the existing trajectory .txt and .npy files in the examples folder. What is the correlation between the .txt file and the .npy files? Ie, could I convert a custom trajectory into the desired .npy file without particlesfm? Thank you.

**Comment by Yuancheng-Xu** [comment]
Hi @fan23j @wzhouxiff @xinntao I am wondering if you have an answer to this? I also would like to convert a .txt file to .npy file but not sure how to do that.

**Comment by wzhouxiff** [comment]
As the ChangeLog describes, we have provided [HandyTrajDrawer](https://github.com/wzhouxiff/HandyTrajDrawer) to customize object trajectories conveniently. Feel free to have a try.
