### ISSUE TITLE
Control failed

### ISSUE THREAD

**Issue by zhw-zhang** [TencentARC/MotionCtrl#6]
Hi, I tested the demo on huggingface. My settings are: 1. control both camera and object motion; 2. the camera poses and trajectory: motion: ['Zoom Out']. speed: 1.0.; 3. trajectories is horizon_1. the prompt is: “A panda crawling on rocks”.  Other parameters are default. But I got the following video, It seems that the control is not very effective.

https://github.com/TencentARC/MotionCtrl/assets/135094935/daa639f0-c250-4587-904a-8a0f5dc6891e

**Comment by wzhouxiff** [comment]
That is the result I generated following your description.

https://github.com/TencentARC/MotionCtrl/assets/19488619/3db037d4-74a1-482e-b16c-c4c879a016a0

**Comment by zhw-zhang** [comment]
Ok, thanks for your reply, maybe there was something wrong when I ran it the first time. I also ran it again and got the same results as you.
